REG_ENTITY(PLAYER, "player")
REG_ENTITY(PICKUP, "pickup")
REG_ENTITY(WEAPON, "weapon")
REG_ENTITY(MINE, "mine")
REG_ENTITY(EXPLOSSION, "explossion")
REG_ENTITY(NUCLEAREXPLOSSION, "nuclear explossion")
#include "REG_ENEMIES.h"